spring.application.name=spring-secure-api
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3308/${spring.application.name}?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=01h45mns
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.format.date=dd/MM/yyyy
application.security.jwt.secret=cG9pbnRhYmlsaXR5bWVhbmZpeGRlYWx3ZXN0c2Fkb3VnaHR0aHJvd25jb21iaW5hdGlvbndpbmRlY2lkZXdhcm5waXRjaGtub3d3aWZlbW9yZW9mZmljaWFsd2hlbmV2ZXJmbG93ZXJjaGVtaWNhbHJlc2VhcmNoYWRkc2hpcGI

